### ISSUE TITLE
how to compile it

### ISSUE THREAD

**Issue by zhouxinlzu** [wangpengcheng/OfflineMapTest#1]
which qt version your compiled? my is 5.8.0 ,but it report error: C1083: “QtLocation/private/qdeclarativegeomapquickitem_p.h”: No such file or directory
how to solve it ?

**Comment by wangpengcheng** [comment]
地图模块至少，需要qt5.11版本，测试过qt5.11.3-5.12.1没有问题

**Comment by wangpengcheng** [comment]
地图用了很多QtLoaction的内部私有模块，这部分源码变动比较大
